# baseURL
@baseURL = http://localhost:4230/super_admin

###
# Find All Accounts
GET {{ baseURL }}/accounts

###
# Find All Accounts with Users
GET {{ baseURL }}/accounts/user

###
# Find Accounts By Id
GET {{ baseURL }}/accounts/635a068f019d4824aeb165d9

###
# Create Accounts
POST {{ baseURL }}/
Content-Type: application/json

{
  "name": "Pinnacle 1",
  "locale_id": "635f5ac9e0bd3766ca2735f8",
  "domain": "Pinnacle1.com",
  "support_email": "supportpinnacle@gmail.com"
}


###
# Modify Accounts By Id
PUT {{ baseURL }}/accounts/635a068f019d4824aeb165d9
Content-Type: application/json
{
    "name": "sami1",
    "displayname":"Sami3 Agent"
}


###
# Delete Accounts By Id
GET {{ baseURL }}/accounts/635a068f019d4824aeb165d9/0
